apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuke
  labels:
    app: nuke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuke
  template
    metadata:
      name: nuke
      labels:
        app: nuke
spec:
      containers:
      - name: nuke
        image: busybox
        command:
        - /bin/sh
        - -c
        - "while true; do wget -q -O- devops-hw; done"